### ISSUE TITLE
ajax error

### ISSUE THREAD

**Issue by red4f** [ShinoNuma/Rewrite-Article-Generator#4]
Missing Database Table
Error: Table synonyms for model Synonym was not found in datasource default.
I assume the xpath query isn't outputting synonymy and needs an update? Tried to modify it to //*[@id="meanings"]/div[2]/ul/li/a but no avail.

**Comment by ShinoNuma** [comment]
The problem in your case is not the XPath query but the database, as the error mention.
In order to solve your problem you need to manually check if you have correctly imported the database, so connect to your MySQL or MariaDB server and see if all the tables are there.

If this is the case then you need to check the database information that you filled in the "config.php" file are correct.

**Comment by red4f** [comment]
After rechecking and make sure the import is done correctly, it worked. Thanks so much for pointing me to the right direction! With some testings, there is a good chance that it fails to rewrite and then it gives "An error has occurred, please try again." It seems to me that by setting it Rewite Level: High Alternate Rewite:Disable has the best chance for success. In my particular case, is it possible to modify some codes and just give the original text in case it fails?
